// Mocks generated by Mockito 5.4.1 from annotations
// in cist_keion_app/test/feature/reservation/data/factories/reservation_factory_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cist_keion_app/feature/reservation/data/factories/institute_time_factory.dart'
    as _i5;
import 'package:cist_keion_app/feature/reservation/data/factories/reserved_member_factory.dart'
    as _i4;
import 'package:cist_keion_app/feature/reservation/data/models/reserved_member_model.dart'
    as _i2;
import 'package:cist_keion_app/feature/reservation/domain/values/institute_time.dart'
    as _i6;
import 'package:cist_keion_app/feature/reservation/domain/values/reserved_member.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReservedMemberModel_0 extends _i1.SmartFake
    implements _i2.ReservedMemberModel {
  _FakeReservedMemberModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReservedMember_1 extends _i1.SmartFake
    implements _i3.ReservedMember {
  _FakeReservedMember_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReservedMemberFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockReservedMemberFactory extends _i1.Mock
    implements _i4.ReservedMemberFactory {
  MockReservedMemberFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReservedMemberModel convertToModel(_i3.ReservedMember? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #convertToModel,
          [entity],
        ),
        returnValue: _FakeReservedMemberModel_0(
          this,
          Invocation.method(
            #convertToModel,
            [entity],
          ),
        ),
      ) as _i2.ReservedMemberModel);
  @override
  _i3.ReservedMember create(_i4.ReservedMemberParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [params],
        ),
        returnValue: _FakeReservedMember_1(
          this,
          Invocation.method(
            #create,
            [params],
          ),
        ),
      ) as _i3.ReservedMember);
  @override
  _i3.ReservedMember createFromModel(_i2.ReservedMemberModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFromModel,
          [model],
        ),
        returnValue: _FakeReservedMember_1(
          this,
          Invocation.method(
            #createFromModel,
            [model],
          ),
        ),
      ) as _i3.ReservedMember);
}

/// A class which mocks [InstituteTimeFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstituteTimeFactory extends _i1.Mock
    implements _i5.InstituteTimeFactory {
  MockInstituteTimeFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String convertToModel(_i6.InstituteTime? entity) => (super.noSuchMethod(
        Invocation.method(
          #convertToModel,
          [entity],
        ),
        returnValue: '',
      ) as String);
  @override
  _i6.InstituteTime create(String? param) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [param],
        ),
        returnValue: _i6.InstituteTime.first,
      ) as _i6.InstituteTime);
  @override
  _i6.InstituteTime createFromModel(String? model) => (super.noSuchMethod(
        Invocation.method(
          #createFromModel,
          [model],
        ),
        returnValue: _i6.InstituteTime.first,
      ) as _i6.InstituteTime);
}
