// Mocks generated by Mockito 5.4.1 from annotations
// in cist_keion_app/test/feature/suggestion/data/factories/suggestion_factory_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cist_keion_app/feature/suggestion/data/factories/suggestion_category_factory.dart'
    as _i2;
import 'package:cist_keion_app/feature/suggestion/domain/values/suggestion_category.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SuggestionCategoryFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockSuggestionCategoryFactory extends _i1.Mock
    implements _i2.SuggestionCategoryFactory {
  MockSuggestionCategoryFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String convertToModel(_i3.SuggestionCategory? entity) => (super.noSuchMethod(
        Invocation.method(
          #convertToModel,
          [entity],
        ),
        returnValue: '',
      ) as String);
  @override
  _i3.SuggestionCategory create(String? param) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [param],
        ),
        returnValue: _i3.SuggestionCategory.live,
      ) as _i3.SuggestionCategory);
  @override
  _i3.SuggestionCategory createFromModel(String? model) => (super.noSuchMethod(
        Invocation.method(
          #createFromModel,
          [model],
        ),
        returnValue: _i3.SuggestionCategory.live,
      ) as _i3.SuggestionCategory);
}
