#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/a1/fvm/versions/stable"
export "FLUTTER_APPLICATION_PATH=/Users/a1/Documents/xcode/flutter/cist_keion_app"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/a1/Documents/xcode/flutter/cist_keion_app/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=Zmxhdm9yPWRldg==,YXBwTmFtZT1DS0EgZGV2,YXBwSWRTdWZmaXg9LmRldg==,RkxVVFRFUl9XRUJfQVVUT19ERVRFQ1Q9dHJ1ZQ==,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC85MGZhM2FlMjhmZTZkZGFlZTFhZjJjMTIwZjAxZTUwMjAxYzE0MDFiLw=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/a1/Documents/xcode/flutter/cist_keion_app/.dart_tool/package_config.json"
export "flavor=dev"
export "appName=CKA dev"
export "appIdSuffix=.dev"
